# Generated by Django 5.2 on 2025-04-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_projectmodel_created_by_taskmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tms.projectmodel'),
        ),
    ]
