# Generated by Django 5.2 on 2025-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_rename_created_by_projectmodel_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
